### PR TITLE
version bump for upcoming release

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
### Fix or Enhancement?

- [ ] All tests passed
- [ ] Add changes to `changelog.md`

### Environment
- OS: Write here
- Go version: Write here

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Minor version bump due to new feature to support MSI user-assigned identity.

**Comment by catalinaperalta** [comment]
Where is the change for this version bump?

**Comment by jhendrixMSFT** [comment]
It's here https://github.com/Azure/azure-amqp-common-go/pull/45

**Comment by jhendrixMSFT** [comment]
We could also consider it a bug fix; it didn't actually add new surface area, however it did enable new functionality.

**Review by catalinaperalta — APPROVED** [review]
lgtm

**Comment by catalinaperalta** [comment]
Got it, thanks! :)

**Pull request merged**
